"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib/supabase";

export default function Auth(){
  const [loading,setLoading]=useState(false); const [msg,setMsg]=useState(""); const [signedIn,setSignedIn]=useState(false);
  useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>setSignedIn(!!data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setSignedIn(!!session)); return()=>subscription.unsubscribe()},[]);
  async function google(){setMsg(""); if(!supabase){setMsg("Supabase is not connected. Add the project URL and publishable key in Vercel.");return} setLoading(true); const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/auth"}}); if(error){setMsg(error.message);setLoading(false)}}
  async function signOut(){if(supabase) await supabase.auth.signOut(); setSignedIn(false)}
  return <div className="mx-auto max-w-5xl px-6 py-12 md:py-20"><div className="grid overflow-hidden rounded-[2.5rem] border border-[#e8e5df] bg-white/80 shadow-[0_24px_70px_rgba(70,65,90,.08)] md:grid-cols-2"><div className="pastel-lavender p-8 md:p-12"><div className="inline-flex rounded-full bg-white/65 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-[#6f6a8f]">Personal learning center</div><h1 className="mt-8 text-4xl font-black tracking-[-.045em] md:text-5xl">One account.<br/>Your progress stays yours.</h1><p className="mt-5 max-w-md leading-7 text-[#686d78]">Sign in with Google to keep attempts, bookmarks, wrong questions and learning history tied to your account.</p><div className="mt-10 grid gap-3"><div className="rounded-2xl bg-white/60 p-4 text-sm font-semibold">✓ Resume unfinished tests</div><div className="rounded-2xl bg-white/60 p-4 text-sm font-semibold">✓ Track accuracy over time</div><div className="rounded-2xl bg-white/60 p-4 text-sm font-semibold">✓ Save questions for later</div></div></div><div className="p-8 md:p-12"><div className="text-sm font-bold text-[#858b94]">Welcome to aptitude.</div><h2 className="mt-3 text-3xl font-black">{signedIn?"You’re signed in":"Continue with Google"}</h2>{signedIn?<><p className="mt-3 text-[#707984]">Your Supabase session is active.</p><button onClick={signOut} className="mt-8 rounded-full border border-[#ddd8e4] px-6 py-3 font-bold">Sign out</button></>:<><p className="mt-3 text-[#707984]">No passwords to remember. Use your Google account and get straight into practice.</p><button disabled={loading} onClick={google} className="mt-8 flex w-full items-center justify-center gap-3 rounded-2xl border border-[#ddd8e4] bg-white px-5 py-3.5 font-bold shadow-sm transition hover:-translate-y-0.5 hover:shadow-md disabled:opacity-60"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#f4e2e9] text-sm">G</span>{loading?"Opening Google…":"Continue with Google"}</button></>}{msg&&<p className="mt-5 rounded-2xl bg-[#f8e5dc] p-4 text-sm text-[#7d5d50]">{msg}</p>}<p className="mt-8 text-xs leading-5 text-[#9298a0]">Google sign-in requires Google to be enabled under Supabase Authentication → Providers and the app URL to be added to the Supabase redirect configuration.</p></div></div></div>}
