import Link from "next/link";
import { appCatalog } from "../lib/data";
import ProgressDashboard from "../components/progress-dashboard";

const cards=[["/tests","Practice Tests","Thirty full-length tests to build speed, confidence and consistency.","pastel-lavender"],["/practice","Practice by Type","Focus on one reasoning style when you want a more targeted session.","pastel-blue"],["/bookmarks","Bookmarks","Keep the questions you want to return to close at hand.","pastel-mint"]];

export default function Home(){return <div className="mx-auto max-w-[1220px] px-5 py-8 md:px-8 md:py-14">
<section className="dream-surface rounded-[2.8rem] px-7 py-16 md:px-14 md:py-24"><div className="relative z-10 max-w-3xl"><p className="eyebrow">A quiet place to practice</p><h1 className="mt-6 text-5xl font-black leading-[.98] tracking-[-.06em] md:text-7xl">Practice with clarity.<br/><span className="font-semibold text-[#858097]">Progress with intention.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-[#77747d] md:text-lg">A thoughtful practice space for aptitude tests — built to help you solve, review and understand where you stand.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/tests" className="rounded-full bg-[#69617f] px-6 py-3 text-sm font-bold text-white shadow-[0_8px_24px_rgba(82,73,106,.16)] transition hover:-translate-y-0.5 hover:bg-[#5f5875]">Begin a test</Link><Link href="/practice" className="rounded-full border border-[#e3dedc] bg-white/75 px-6 py-3 text-sm font-bold text-[#5f5b66] transition hover:-translate-y-0.5">Explore by type</Link></div></div></section>
<section className="mt-16"><div className="mb-6"><p className="eyebrow">Practice space</p><h2 className="mt-2 text-2xl font-black tracking-[-.035em]">Choose your way in</h2></div><div className="grid gap-4 md:grid-cols-3">{cards.map(([href,title,desc,color])=><Link key={href} href={href} className={`soft-card ${color} group rounded-[2rem] p-7 transition duration-300 hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(60,54,70,.08)]`}><div className="flex items-start justify-between gap-5"><div><h3 className="text-lg font-black tracking-[-.02em]">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-[#77747d]">{desc}</p></div><span className="text-lg text-[#8e8995] transition-transform group-hover:translate-x-1">↗</span></div></Link>)}</div></section>
<section className="mt-16"><ProgressDashboard compact/></section>
<section className="mt-16 border-t border-[#e8e3e0] pt-8"><div className="flex flex-wrap gap-x-8 gap-y-3 text-sm text-[#8b8790]"><span><b className="text-[#383640]">{appCatalog.stats.test_count}</b> curated tests</span><span><b className="text-[#383640]">{appCatalog.stats.question_count.toLocaleString()}</b> questions indexed</span><span><b className="text-[#383640]">{appCatalog.pillars.length}</b> reasoning pillars</span></div></section>
</div>}
