"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { appCatalog, questionsForTest } from "../lib/data";
import { getAttempts, getBookmarks, getWrongQuestions } from "../lib/progress";

const norm=(v:unknown)=>String(v??"").trim().toLowerCase();
const pct=(n:number,d:number)=>d?Math.round((n/d)*100):0;

export default function ProgressDashboard({compact=false}:{compact?:boolean}){
 const [attempts,setAttempts]=useState<any[]>([]); const [bookmarks,setBookmarks]=useState(0); const [wrong,setWrong]=useState(0);
 useEffect(()=>{setAttempts(getAttempts());setBookmarks(getBookmarks().length);setWrong(getWrongQuestions().length)},[]);
 const latest=useMemo(()=>{const map=new Map<string,any>();attempts.filter(a=>a.completedAt).sort((a,b)=>new Date(b.completedAt).getTime()-new Date(a.completedAt).getTime()).forEach(a=>{if(!map.has(a.testId))map.set(a.testId,a)});return map},[attempts]);
 const completed=[...latest.values()];
 const stats=useMemo(()=>{let answered=0,correct=0;latest.forEach(a=>{questionsForTest(a.testId).forEach((q:any)=>{if(a.answers?.[q.id]){answered++;if(norm(a.answers[q.id])===norm(q.a))correct++;}})});const total=appCatalog.stats.question_count;return {answered,correct,accuracy:pct(correct,answered),coverage:pct(answered,total)}},[latest]);
 const pillars=useMemo(()=>appCatalog.pillars.map((p:any)=>{let answered=0,correct=0;latest.forEach((a:any)=>{const test=appCatalog.tests.find((t:any)=>t.test_id===a.testId);if(test?.pillar===p.id)questionsForTest(a.testId).forEach((q:any)=>{if(a.answers?.[q.id]){answered++;if(norm(a.answers[q.id])===norm(q.a))correct++;}})});return {...p,answered,correct,accuracy:pct(correct,answered)};}),[latest]);
 if(compact)return <section className="soft-card rounded-[2rem] p-7 md:p-8"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#8a9098]">Your progress</p><h2 className="mt-2 text-2xl font-black">Keep your momentum</h2></div><Link href="/dashboard" className="text-sm font-bold text-[#69628a]">Full dashboard →</Link></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#f0edf7] p-5"><div className="text-2xl font-black">{completed.length}/{appCatalog.tests.length}</div><div className="mt-1 text-xs font-semibold text-[#737982]">Tests completed</div></div><div className="rounded-2xl bg-[#eaf2f7] p-5"><div className="text-2xl font-black">{stats.accuracy}%</div><div className="mt-1 text-xs font-semibold text-[#737982]">Accuracy</div></div><div className="rounded-2xl bg-[#edf3ee] p-5"><div className="text-2xl font-black">{stats.answered}/{appCatalog.stats.question_count}</div><div className="mt-1 text-xs font-semibold text-[#737982]">Questions answered</div></div></div></section>;
 return <div className="space-y-8">
  <section className="soft-card rounded-[2.25rem] p-7 md:p-9"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#8a9098]">Overview</p><h1 className="mt-2 text-4xl font-black tracking-[-.04em]">Your progress</h1><p className="mt-2 text-sm text-[#737982]">A clear view of completion, accuracy and where to focus next.</p></div><div className="text-right"><div className="text-4xl font-black">{stats.coverage}%</div><div className="text-xs font-bold text-[#8a9098]">of question bank answered</div></div></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-[#eceae5]"><div className="h-full rounded-full bg-[#8f89aa]" style={{width:`${stats.coverage}%`}}/></div><div className="mt-7 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-[#f0edf7] p-5"><b className="text-2xl">{completed.length}/{appCatalog.tests.length}</b><div className="mt-1 text-xs text-[#737982]">Tests completed</div></div><div className="rounded-2xl bg-[#eaf2f7] p-5"><b className="text-2xl">{stats.answered}/{appCatalog.stats.question_count}</b><div className="mt-1 text-xs text-[#737982]">Questions answered</div></div><div className="rounded-2xl bg-[#edf3ee] p-5"><b className="text-2xl">{stats.accuracy}%</b><div className="mt-1 text-xs text-[#737982]">Overall accuracy</div></div><div className="rounded-2xl bg-[#f5eee5] p-5"><b className="text-2xl">{wrong}</b><div className="mt-1 text-xs text-[#737982]">Wrong to review</div></div></div></section>
  <section className="soft-card rounded-[2.25rem] p-7 md:p-9"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#8a9098]">By reasoning type</p><h2 className="mt-2 text-2xl font-black">Strengths & gaps</h2></div><span className="text-xs font-semibold text-[#8a9098]">Answered · accuracy</span></div><div className="mt-7 space-y-5">{pillars.map((p:any)=><div key={p.id}><div className="flex justify-between gap-4 text-sm"><div><span className="font-bold">{p.name}</span><span className="ml-2 text-[#9a9ea4]">{p.answered} answered</span></div><b>{p.accuracy}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#eeece7]"><div className="h-full rounded-full bg-[#9a94b4]" style={{width:`${p.accuracy}%`}}/></div></div>)}</div></section>
  <section className="soft-card rounded-[2.25rem] p-7 md:p-9"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#8a9098]">All tests</p><h2 className="mt-2 text-2xl font-black">30-test progress</h2></div><Link href="/tests" className="text-sm font-bold text-[#69628a]">Practice tests →</Link></div><div className="mt-6 divide-y divide-[#eeeae5]">{appCatalog.tests.map((t:any,i:number)=>{const a=latest.get(t.test_id);const qs=questionsForTest(t.test_id);let c=0;let ans=0;if(a){qs.forEach((q:any)=>{if(a.answers?.[q.id]){ans++;if(norm(a.answers[q.id])===norm(q.a))c++;}})}const accuracy=pct(c,ans);return <Link href={`/tests/${t.test_id}`} key={t.test_id} className="group flex items-center gap-4 py-4"><span className="w-10 text-xs font-black text-[#9a9ea4]">{String(i+1).padStart(2,"0")}</span><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{t.title.replaceAll("_"," ")}</div><div className="mt-1 text-xs text-[#8a9098]">{ans?`${c}/${qs.length} correct · ${accuracy}% accuracy`:"Not started"}</div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#eeece7]"><div className="h-full rounded-full bg-[#879d8b]" style={{width:`${a?accuracy:0}%`}}/></div></div><span className={`shrink-0 rounded-full px-3 py-1 text-[11px] font-black ${a?"bg-[#edf3ee] text-[#667d6c]":"bg-[#f7f5f1] text-[#92969c]"}`}>{a?"Completed":"Not started"}</span></Link>})}</div></section>
  <div className="grid gap-4 md:grid-cols-2"><Link href="/bookmarks" className="soft-card rounded-[2rem] p-6"><div className="text-xs font-black uppercase tracking-[.16em] text-[#8a9098]">Saved</div><div className="mt-2 text-2xl font-black">{bookmarks} bookmarks</div><p className="mt-1 text-sm text-[#737982]">Questions you chose to revisit.</p></Link><Link href="/tests" className="soft-card rounded-[2rem] p-6"><div className="text-xs font-black uppercase tracking-[.16em] text-[#8a9098]">Next</div><div className="mt-2 text-2xl font-black">Continue practicing</div><p className="mt-1 text-sm text-[#737982]">Pick an unfinished test and keep going.</p></Link></div>
 </div>;
}
