"use client";
import {useEffect,useRef,useState} from "react";
import {appCatalog,questionsForTest} from "../lib/data";
import {getAttempts,getPracticeDays} from "../lib/progress";
import {supabase} from "../lib/supabase";

type Kind="profile"|"dashboard"|"result";
type Props={kind:Kind;result?:{title:string;correct:number;total:number;accuracy:number;duration:string}};
const pad=(n:number)=>String(n).padStart(2,"0");
const key=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const getStreak=(days:string[])=>{const s=new Set(days);const d=new Date();d.setHours(0,0,0,0);if(!s.has(key(d)))d.setDate(d.getDate()-1);let n=0;while(s.has(key(d))){n++;d.setDate(d.getDate()-1)}return n};
const box=(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,fill:string)=>{c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill()};
const label=(c:CanvasRenderingContext2D,v:string,x:number,y:number,size:number,weight:number,fill:string)=>{c.fillStyle=fill;c.font=`${weight} ${size}px Arial`;c.fillText(v,x,y)};
export default function ShareCard({kind,result}:Props){
 const [open,setOpen]=useState(false),[format,setFormat]=useState<"wide"|"story">("wide");const canvas=useRef<HTMLCanvasElement>(null);
 const [data,setData]=useState({streak:0,completed:0,answered:0,accuracy:0,days:[] as string[],pillars:[] as {name:string;accuracy:number;answered:number}[]});
 useEffect(()=>{if(!open)return;(async()=>{const s=await supabase?.auth.getSession();const uid=s?.data.session?.user?.id||"";const attempts=getAttempts().filter(a=>a.completedAt);let answered=0,correct=0;attempts.forEach(a=>questionsForTest(a.testId).forEach((q:any)=>{if(a.answers?.[q.id]){answered++;if(String(a.answers[q.id]).trim().toLowerCase()===String(q.a??"").trim().toLowerCase())correct++}}));const days=uid?getPracticeDays(uid):[];const pillars=appCatalog.pillars.map((p:any)=>{let a=0,c=0;attempts.forEach(at=>{const t=appCatalog.tests.find((z:any)=>z.test_id===at.testId);if(t?.pillar===p.id)questionsForTest(at.testId).forEach((q:any)=>{if(at.answers?.[q.id]){a++;if(String(at.answers[q.id]).trim().toLowerCase()===String(q.a??"").trim().toLowerCase())c++}})});return {name:p.name,answered:a,accuracy:a?Math.round(c/a*100):0}});setData({streak:uid?getStreak(days):0,completed:attempts.length,answered,accuracy:answered?Math.round(correct/answered*100):0,days,pillars})})()},[open,kind]);
 useEffect(()=>{const c=canvas.current;if(!c||!open)return;const story=format==="story";const w=story?1080:1200,h=story?1920:630,l=story?90:70;c.width=w;c.height=h;const x=c.getContext("2d")!;const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,"#d8c9ea");g.addColorStop(.35,"#dcecf1");g.addColorStop(.7,"#f0dce7");g.addColorStop(1,"#f8e9df");x.fillStyle=g;x.fillRect(0,0,w,h);label(x,"aptitude.",l,62,30,800,"#302d36");label(x,kind==="dashboard"?"MY PRACTICE JOURNEY":kind==="result"?"TEST RESULT":"A QUIET PLACE TO PRACTICE",l,102,13,700,"#77717f");
 if(kind==="dashboard"){const top=story?260:180;label(x,String(data.streak),l,top+65,story?88:76,900,"#302d36");label(x,"DAY STREAK",l+(story?220:160),top+62,story?24:21,800,"#77717f");label(x,"Keep showing up. One day at a time.",l,top+108,story?19:16,500,"#77717f");const bw=story?900:500;box(x,l,top+140,bw,story?24:18,12,"rgba(255,255,255,.58)");box(x,l,top+140,bw*Math.min(data.completed/appCatalog.tests.length,1),story?24:18,12,"#9a7faf");label(x,`${data.completed}/${appCatalog.tests.length} tests completed`,l,top+182,15,700,"#5e5865");const py=story?590:335;label(x,"LEARNING PROGRESSION",l,py,14,800,"#4c4653");data.pillars.forEach((p,i)=>{const y=py+35+i*(story?76:46);box(x,l,y,bw,story?60:36,16,"rgba(255,255,255,.5)");label(x,p.name,l+15,y+22,story?15:12,800,"#4c4653");label(x,p.answered?`${p.accuracy}% · ${p.answered} answered`:"Not started",l+15,y+(story?45:0),story?11:9,600,"#77717f");const bx=l+(story?410:245),tw=bw-(bx-l)-20;box(x,bx,y+(story?26:14),tw,8,8,"rgba(255,255,255,.7)");box(x,bx,y+(story?26:14),tw*p.accuracy/100,8,8,"#9a7faf")});const now=new Date(),count=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),first=new Date(now.getFullYear(),now.getMonth(),1),off=first.getDay(),gy=story?1160:525,cell=story?52:24,gap=story?12:7;label(x,"STREAK · THIS MONTH",l,gy,14,800,"#4c4653");for(let i=0;i<count;i++){const idx=i+off,d=new Date(now.getFullYear(),now.getMonth(),i+1),xx=l+(idx%7)*(cell+gap),yy=gy+28+Math.floor(idx/7)*(cell+gap);box(x,xx,yy,cell,cell,cell/3,data.days.includes(key(d))?"#9a7faf":"rgba(255,255,255,.5)");label(x,String(i+1),xx+cell/2-4,yy+cell/2+4,story?11:8,700,data.days.includes(key(d))?"#fff":"#817b86")};label(x,`${data.days.length} practice days · ${data.answered} questions · ${data.accuracy}% accuracy`,l,story?1620:600,story?16:12,700,"#5e5865")}
 else if(kind==="result"&&result){const y=story?280:205;label(x,result.title.slice(0,30),l,y,story?38:42,900,"#302d36");label(x,`${result.accuracy}%`,l,y+105,story?100:86,900,"#6d6388");label(x,`${result.correct}/${result.total} correct`,l,y+150,story?22:19,700,"#77717f");label(x,`${result.duration} spent`,l,y+182,story?18:17,600,"#77717f");const bw=story?900:500;box(x,l,y+220,bw,story?26:18,12,"rgba(255,255,255,.58)");box(x,l,y+220,bw*result.accuracy/100,story?26:18,12,"#9a7faf");const items=[[String(result.correct),"CORRECT"],[String(result.total-result.correct),"WRONG / SKIPPED"],[result.duration,"TIME SPENT"]];items.forEach((it,i)=>{const cw=story?280:190,xx=l+i*(cw+20),yy=y+285;box(x,xx,yy,cw,story?150:105,20,"rgba(255,255,255,.52)");label(x,it[0],xx+18,yy+48,story?32:24,800,"#403b45");label(x,it[1],xx+18,yy+80,story?13:11,700,"#77717f")})}
 else {label(x,"Practice with clarity.",l,story?250:220,story?48:50,900,"#302d36");label(x,"A little progress, made visible.",l,story?300:265,20,500,"#77717f");[[appCatalog.tests.length,"CURATED TESTS"],[appCatalog.stats.question_count,"QUESTIONS"],[appCatalog.pillars.length,"REASONING PILLARS"]].forEach((it,i)=>{const cw=story?900:330,ch=story?185:110,xx=story?l:l+i*(cw+18),yy=story?430:335;box(x,xx,yy,cw,ch,22,"rgba(255,255,255,.52)");label(x,String(it[0]),xx+24,yy+58,story?36:28,900,"#403b45");label(x,String(it[1]),xx+24,yy+88,story?13:11,700,"#77717f")})}
 label(x,"aptitude · practice with intention",l,h-(story?70:32),12,600,"#77717f")
 },[open,format,kind,result,data]);
 const save=()=>{const c=canvas.current;if(!c)return;const a=document.createElement("a");a.download=`aptitude-${kind}-${format}.png`;a.href=c.toDataURL("image/png");a.click()};const share=async()=>{const url=window.location.href;try{if(navigator.share){await navigator.share({title:"aptitude.",text:kind==="result"?`I scored ${result?.accuracy}% on an aptitude practice test.`:"My aptitude practice progress",url});return}}catch{}try{await navigator.clipboard.writeText(url);alert("Link copied!")}catch{alert(url)}};
 return <><button onClick={()=>setOpen(true)} className="rounded-full border border-[#ddd8e4] bg-white/80 px-5 py-2.5 text-sm font-bold text-[#5f597b] shadow-sm">↗ Share</button>{open&&<div className="fixed inset-0 z-[100] grid place-items-center bg-[#302d36]/35 p-4 backdrop-blur-sm"><div className="w-full max-w-4xl rounded-[2rem] border border-white/70 bg-[#fbfaf9] p-5 shadow-2xl md:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow">Share</p><h2 className="mt-2 text-2xl font-black">Choose your format</h2></div><button onClick={()=>setOpen(false)} className="rounded-full bg-white px-3 py-2 font-bold">✕</button></div><div className="mt-5 flex gap-2"><button onClick={()=>setFormat("wide")} className={`rounded-full px-4 py-2 text-sm font-bold ${format==="wide"?"bg-[#6d6388] text-white":"bg-white text-[#66616b]"}`}>Website · 1200×630</button><button onClick={()=>setFormat("story")} className={`rounded-full px-4 py-2 text-sm font-bold ${format==="story"?"bg-[#6d6388] text-white":"bg-white text-[#66616b]"}`}>Story · 1080×1920</button></div><div className="mt-5 max-h-[62vh] overflow-auto rounded-[1.5rem] border border-[#e8e2e7] bg-white"><canvas ref={canvas} className="block h-auto w-full"/></div><div className="mt-5 flex justify-end gap-2"><button onClick={save} className="rounded-full bg-[#6d6388] px-5 py-2.5 text-sm font-bold text-white">↓ Save image</button><button onClick={share} className="rounded-full border border-[#ddd8e4] bg-white px-5 py-2.5 text-sm font-bold">Share / copy link</button></div></div></div>}</>;
}
