"use client";
import {useEffect,useRef,useState} from "react";
import {getAttempts,getPracticeDays} from "../lib/progress";
import {supabase} from "../lib/supabase";
type Kind="profile"|"dashboard"|"result"; type Props={kind:Kind;result?:{title:string;correct:number;total:number;accuracy:number;duration:string}};
const pad=(n:number)=>String(n).padStart(2,"0"); const dayKey=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const calcStreak=(days:string[])=>{const s=new Set(days);const d=new Date();d.setHours(0,0,0,0);if(!s.has(dayKey(d)))d.setDate(d.getDate()-1);let n=0;while(s.has(dayKey(d))){n++;d.setDate(d.getDate()-1)}return n};
export default function ShareCard({kind,result}:Props){
 const [open,setOpen]=useState(false),[format,setFormat]=useState<"wide"|"story">("wide");const canvas=useRef<HTMLCanvasElement>(null);const [stats,setStats]=useState({streak:0,completed:0,days:0});
 useEffect(()=>{if(!open||kind!=="dashboard")return;(async()=>{const session=await supabase?.auth.getSession();const uid=session?.data.session?.user?.id||"";const attempts=getAttempts().filter(a=>a.completedAt);setStats({streak:uid?calcStreak(getPracticeDays(uid)):0,completed:attempts.length,days:uid?getPracticeDays(uid).length:0})})()},[open,kind]);
 useEffect(()=>{const c=canvas.current;if(!c||!open)return;const w=format==="wide"?1200:1920,h=format==="wide"?630:1080;c.width=w;c.height=h;const x=c.getContext("2d")!;const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,"#eee7f7");g.addColorStop(.48,"#e7f0f5");g.addColorStop(1,"#f5e4e9");x.fillStyle=g;x.fillRect(0,0,w,h);const l=format==="wide"?72:110;const fs=(n:number)=>format==="wide"?n:Math.round(n*1.48);x.fillStyle="#302d36";x.font=`800 ${fs(34)}px Arial`;x.fillText("aptitude.",l,format==="wide"?78:115);x.fillStyle="#77717f";x.font=`700 ${fs(17)}px Arial`;x.fillText(kind==="profile"?"A quiet place to practice":kind==="dashboard"?"MY PRACTICE JOURNEY":"TEST RESULT",l,format==="wide"?122:175);
 if(kind==="profile"){x.fillStyle="#302d36";x.font=`800 ${fs(58)}px Arial`;x.fillText("Practice with clarity.",l,format==="wide"?260:380);x.fillStyle="#77717f";x.font=`500 ${fs(28)}px Arial`;x.fillText("Solve · review · progress · repeat",l,format==="wide"?315:445)}
 if(kind==="dashboard"){const y=format==="wide"?245:390;x.fillStyle="#302d36";x.font=`900 ${fs(82)}px Arial`;x.fillText(String(stats.streak),l,y);x.fillStyle="#77717f";x.font=`700 ${fs(25)}px Arial`;x.fillText("day streak",format==="wide"?190:290,y);x.fillStyle="#302d36";x.font=`800 ${fs(32)}px Arial`;x.fillText(`${stats.completed} tests completed`,l,y+65);x.fillText(`${stats.days} practice days`,l,y+110)}
 if(kind==="result"&&result){const y=format==="wide"?255:400;x.fillStyle="#302d36";x.font=`900 ${fs(48)}px Arial`;x.fillText(result.title.slice(0,28),l,y);x.font=`900 ${fs(92)}px Arial`;x.fillText(`${result.accuracy}%`,l,y+105);x.fillStyle="#77717f";x.font=`700 ${fs(24)}px Arial`;x.fillText(`${result.correct}/${result.total} correct · ${result.duration} spent`,format==="wide"?290:435,y+105)}
 x.fillStyle="#77717f";x.font=`600 ${fs(14)}px Arial`;x.fillText("aptitude · practice with intention",w-(format==="wide"?300:450),h-(format==="wide"?35:55));},[open,format,kind,result,stats]);
 const save=()=>{const c=canvas.current;if(!c)return;const a=document.createElement("a");a.download=`aptitude-${kind}-${format}.png`;a.href=c.toDataURL("image/png");a.click()};
 const share=async()=>{const url=window.location.href;try{if(navigator.share){await navigator.share({title:"aptitude.",text:kind==="result"?`I scored ${result?.accuracy}% on an aptitude practice test.`:"My aptitude practice progress",url});return}}catch{}try{await navigator.clipboard.writeText(url);alert("Link copied!")}catch{alert(url)}};
 return <><button onClick={()=>setOpen(true)} className="rounded-full border border-[#ddd8e4] bg-white/80 px-5 py-2.5 text-sm font-bold text-[#5f597b] shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">↗ Share</button>{open&&<div className="fixed inset-0 z-[100] grid place-items-center bg-[#302d36]/35 p-4 backdrop-blur-sm"><div className="w-full max-w-4xl rounded-[2rem] border border-white/70 bg-[#fbfaf9] p-5 shadow-[0_30px_100px_rgba(40,35,50,.2)] md:p-7"><div className="flex items-center justify-between"><div><p className="eyebrow">Share</p><h2 className="mt-2 text-2xl font-black">Choose your format</h2></div><button onClick={()=>setOpen(false)} className="rounded-full bg-white px-3 py-2 font-bold">✕</button></div><div className="mt-5 flex gap-2"><button onClick={()=>setFormat("wide")} className={`rounded-full px-4 py-2 text-sm font-bold ${format==="wide"?"bg-[#6d6388] text-white":"bg-white text-[#66616b]"}`}>Website · 1200×630</button><button onClick={()=>setFormat("story")} className={`rounded-full px-4 py-2 text-sm font-bold ${format==="story"?"bg-[#6d6388] text-white":"bg-white text-[#66616b]"}`}>16:9 · 1920×1080</button></div><div className="mt-5 overflow-hidden rounded-[1.5rem] border border-[#e8e2e7] bg-white"><canvas ref={canvas} className="block h-auto w-full"/></div><div className="mt-5 flex justify-end gap-2"><button onClick={save} className="rounded-full bg-[#6d6388] px-5 py-2.5 text-sm font-bold text-white">↓ Save image</button><button onClick={share} className="rounded-full border border-[#ddd8e4] bg-white px-5 py-2.5 text-sm font-bold">Share / copy link</button></div></div></div>}</>;
}
