"use client";
import {useMemo,useState} from "react"; import {useParams,useRouter} from "next/navigation"; import {appCatalog,questionsForTest,pillarMap} from "../../../lib/data";

export default function TestPage(){
  const {testId}=useParams<{testId:string}>(); const router=useRouter(); const test=appCatalog.tests.find((x:any)=>x.test_id===testId); const qs=useMemo(()=>questionsForTest(testId),[testId]); const [started,setStarted]=useState(false); const [idx,setIdx]=useState(0); const [answers,setAnswers]=useState<Record<string,string>>({});
  if(!test)return <div className="mx-auto max-w-3xl px-6 py-16"><div className="rounded-[2rem] bg-[#f8e5dc] p-8"><h1 className="text-3xl font-black">Test not found</h1><button onClick={()=>router.push("/tests")} className="mt-6 rounded-full bg-[#6f6a8f] px-5 py-2.5 font-bold text-white">Back to tests</button></div></div>;
  if(!started)return <div className="mx-auto max-w-5xl px-6 py-12 md:py-16"><div className="pastel-lavender overflow-hidden rounded-[2.5rem] p-8 md:p-12"><p className="text-xs font-black uppercase tracking-[.18em] text-[#756f92]">{pillarMap[test.pillar]} · TEST {testId.replace("TEST_","")}</p><h1 className="mt-5 text-5xl font-black tracking-[-.045em]">{test.title.replaceAll("_"," ")}</h1><div className="mt-6 flex flex-wrap gap-2 text-sm font-bold text-[#6c7180]"><span className="rounded-full bg-white/70 px-4 py-2">{test.question_count} questions</span><span className="rounded-full bg-white/70 px-4 py-2">Timed practice</span><span className="rounded-full bg-white/70 px-4 py-2">{qs.length?"Question bank loaded":"Question bank unavailable"}</span></div><p className="mt-6 max-w-2xl leading-7 text-[#666d79]">Your answers stay in this session while you move through the test.</p><button onClick={()=>setStarted(true)} disabled={!qs.length} className="mt-9 rounded-full bg-[#6f6a8f] px-7 py-3.5 font-bold text-white shadow-sm disabled:cursor-not-allowed disabled:opacity-40">{qs.length?"Start test →":"No questions loaded"}</button></div></div>;
  const q=qs[idx]; if(!q)return <div className="mx-auto max-w-3xl px-6 py-16"><div className="pastel-peach rounded-[2rem] p-8"><h1 className="text-3xl font-black">Question data is not loaded</h1><p className="mt-3 leading-7 text-[#6f7782]">This test is in the catalog, but its question records are missing from the current build.</p><button onClick={()=>router.push("/tests")} className="mt-6 rounded-full bg-[#6f6a8f] px-5 py-2.5 font-bold text-white">Back to tests</button></div></div>;
  const opts=(q.o||[]) as any[]; const answer=answers[q.id]||""; const label=q.subquestion?`Question ${q.number}${q.subquestion}`:`Question ${q.number}`; const progress=((idx+1)/Math.max(qs.length,1))*100;
  return <div className="mx-auto max-w-5xl px-6 py-8 md:py-12"><div className="mb-5 flex items-center justify-between"><div><div className="text-sm font-black">{label} <span className="font-normal text-[#8a9098]">/ {qs.length}</span></div><div className="mt-1 text-xs text-[#8a9098]">{pillarMap[test.pillar]}</div></div><button onClick={()=>router.push("/tests")} className="rounded-full px-4 py-2 text-sm font-bold text-[#707984] hover:bg-white">Exit</button></div><div className="mb-7 h-2 overflow-hidden rounded-full bg-[#ebe9e5]"><div className="h-full rounded-full bg-[#9b94bd] transition-all" style={{width:`${progress}%`}}/></div><article className="soft-card rounded-[2.25rem] p-7 md:p-10"><div className="text-xl font-semibold leading-9 md:text-2xl">{q.t}</div>{opts.length>0?<div className="mt-9 grid gap-3">{opts.map((o:any,i:number)=>{const val=typeof o==="string"?o:(o.text||o.label||o.option||"");return <button key={i} onClick={()=>setAnswers({...answers,[q.id]:val})} className={`rounded-2xl border p-4 text-left transition ${answer===val?"border-[#9b94bd] bg-[#f0edf8]":"border-[#e5e2dc] bg-white hover:border-[#cfc9db]"}`}><span className="mr-3 inline-flex h-8 w-8 items-center justify-center rounded-full bg-[#f1eff4] text-xs font-black">{String.fromCharCode(65+i)}</span>{val}</button>})}</div>:<div className="mt-9"><label className="text-sm font-bold text-[#69717b]">Your answer</label><input value={answer} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})} placeholder="Type your answer…" className="mt-2 w-full rounded-2xl border border-[#e3e0da] bg-white px-4 py-4 outline-none transition focus:border-[#9b94bd] focus:ring-4 focus:ring-[#e9e4f7]"/><p className="mt-3 rounded-2xl bg-[#f8f6f1] p-4 text-xs leading-5 text-[#858b94]">This item comes from a source question set whose answer choices are visual or free-response.</p></div>}</article><div className="mt-6 flex justify-between"><button disabled={idx===0} onClick={()=>setIdx(Math.max(0,idx-1))} className="rounded-full border border-[#ddd9d2] bg-white px-5 py-2.5 font-bold disabled:opacity-30">Previous</button>{idx<qs.length-1?<button onClick={()=>setIdx(idx+1)} className="rounded-full bg-[#6f6a8f] px-6 py-2.5 font-bold text-white">Next →</button>:<button onClick={()=>router.push("/history")} className="rounded-full bg-[#6f6a8f] px-6 py-2.5 font-bold text-white">Finish test</button>}</div></div>
}
